### ISSUE TITLE
Dropdown clicks not captured reliably

### ISSUE THREAD

**Issue by chris-aeviator** [Point72/raydar#50]
**Describe the bug**
When hitting the theme dropdown, a click will not always open the dropdown selection.

**To Reproduce**
1. Go to Themes
2. click the dropdown

**Expected behavior**
The dropdown selection "overlay" should not directly close again.

**Screenshots**

https://github.com/user-attachments/assets/9a64d700-e337-493a-b706-2830e3791fa0

**Desktop (please complete the following information):**
 - OS: MacOS 14, Linux
 - Firefox

**Additional context**
I have 50% less sucess in succeeding (keeping the dropdown open) on Linux

**Comment by timkpaine** [comment]
https://github.com/finos/perspective/issues/2693
